services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: anubis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
    image: ghcr.io/taldoflemis/anubis:latest
    environment:
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: anubis
      APP_PORT: 3000
      APP_SESSION_SECRET: superdupersecrethereasdfasdfasdfasdfasdfasdfasdfasdfasdfasfdasfasdf
      APP_CORS_ORIGIN: http://localhost:5173

      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret

      AUTH_CONFIRM_EMAIL_SECRET: your-confirm-email-secret-min-32-chars-long
      AUTH_CONFIRM_EMAIL_EXPIRES_IN: 1d
      AUTH_FORGOT_SECRET: your-forgot-password-secret-min-32-chars-long
      AUTH_FORGOT_EXPIRES_IN: 30m

      FRONTEND_URL: http://localhost:5173

      MAIL_TRANSPORT: smtp

      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USER:
      MAIL_PASSWORD:
      MAIL_DEFAULT_FROM: noreply@anubis.local

      MAIL_GOOGLE_CLIENT_ID:
      MAIL_GOOGLE_CLIENT_SECRET:
      MAIL_GOOGLE_REFRESH_TOKEN:
      MAIL_GOOGLE_USER: tubias@gmail.com

      ADMIN_PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    healthcheck:
      test: ['CMD-SHELL', 'wget http://localhost:8025 -O /dev/null']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend/
    image: ghcr.io/taldoflemis/anubis/frontend:latest
    ports:
      - 5173:8080
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_GOOGLE_CLIENT_ID: your-google-client-id