/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmNewEmailRouteImport } from './routes/auth/confirm-new-email'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth/confirm-email'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AppResearchThemesRouteImport } from './routes/_app/research-themes'
import { Route as AuthOnboardingIndexRouteImport } from './routes/auth/onboarding/index'
import { Route as AppValidationIndexRouteImport } from './routes/_app/validation/index'
import { Route as AppEnrollmentIndexRouteImport } from './routes/_app/enrollment/index'
import { Route as AuthOnboardingSecretaryRouteImport } from './routes/auth/onboarding/secretary'
import { Route as AuthOnboardingProfessorRouteImport } from './routes/auth/onboarding/professor'
import { Route as AppValidationEnrollmentIdRouteImport } from './routes/_app/validation/$enrollmentId'
import { Route as AppManageResearchThemesRouteImport } from './routes/_app/manage/research-themes'
import { Route as AppManageProfessorsRouteImport } from './routes/_app/manage/professors'
import { Route as AppManageEnrollmentPeriodsRouteImport } from './routes/_app/manage/enrollment-periods'
import { Route as AppEnrollmentNewRouteImport } from './routes/_app/enrollment/new'
import { Route as AppEnrollmentNewIndexRouteImport } from './routes/_app/enrollment/new/index'
import { Route as AppManageEnrollmentsIdRouteImport } from './routes/_app/manage/enrollments.$id'
import { Route as AppEnrollmentNewThemesRouteImport } from './routes/_app/enrollment/new/themes'
import { Route as AppEnrollmentNewSigaaRouteImport } from './routes/_app/enrollment/new/sigaa'
import { Route as AppEnrollmentNewReviewRouteImport } from './routes/_app/enrollment/new/review'
import { Route as AppEnrollmentNewPoscompRouteImport } from './routes/_app/enrollment/new/poscomp'
import { Route as AppEnrollmentNewLevelRouteImport } from './routes/_app/enrollment/new/level'
import { Route as AppEnrollmentNewCvRouteImport } from './routes/_app/enrollment/new/cv'
import { Route as AppEnrollmentNewAcademicRouteImport } from './routes/_app/enrollment/new/academic'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmNewEmailRoute = AuthConfirmNewEmailRouteImport.update({
  id: '/confirm-new-email',
  path: '/confirm-new-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppResearchThemesRoute = AppResearchThemesRouteImport.update({
  id: '/research-themes',
  path: '/research-themes',
  getParentRoute: () => AppRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthRoute,
} as any)
const AppValidationIndexRoute = AppValidationIndexRouteImport.update({
  id: '/validation/',
  path: '/validation/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentIndexRoute = AppEnrollmentIndexRouteImport.update({
  id: '/enrollment/',
  path: '/enrollment/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOnboardingSecretaryRoute = AuthOnboardingSecretaryRouteImport.update({
  id: '/onboarding/secretary',
  path: '/onboarding/secretary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingProfessorRoute = AuthOnboardingProfessorRouteImport.update({
  id: '/onboarding/professor',
  path: '/onboarding/professor',
  getParentRoute: () => AuthRoute,
} as any)
const AppValidationEnrollmentIdRoute =
  AppValidationEnrollmentIdRouteImport.update({
    id: '/validation/$enrollmentId',
    path: '/validation/$enrollmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppManageResearchThemesRoute = AppManageResearchThemesRouteImport.update({
  id: '/manage/research-themes',
  path: '/manage/research-themes',
  getParentRoute: () => AppRoute,
} as any)
const AppManageProfessorsRoute = AppManageProfessorsRouteImport.update({
  id: '/manage/professors',
  path: '/manage/professors',
  getParentRoute: () => AppRoute,
} as any)
const AppManageEnrollmentPeriodsRoute =
  AppManageEnrollmentPeriodsRouteImport.update({
    id: '/manage/enrollment-periods',
    path: '/manage/enrollment-periods',
    getParentRoute: () => AppRoute,
  } as any)
const AppEnrollmentNewRoute = AppEnrollmentNewRouteImport.update({
  id: '/enrollment/new',
  path: '/enrollment/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentNewIndexRoute = AppEnrollmentNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppManageEnrollmentsIdRoute = AppManageEnrollmentsIdRouteImport.update({
  id: '/manage/enrollments/$id',
  path: '/manage/enrollments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEnrollmentNewThemesRoute = AppEnrollmentNewThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewSigaaRoute = AppEnrollmentNewSigaaRouteImport.update({
  id: '/sigaa',
  path: '/sigaa',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewReviewRoute = AppEnrollmentNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewPoscompRoute = AppEnrollmentNewPoscompRouteImport.update({
  id: '/poscomp',
  path: '/poscomp',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewLevelRoute = AppEnrollmentNewLevelRouteImport.update({
  id: '/level',
  path: '/level',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewCvRoute = AppEnrollmentNewCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => AppEnrollmentNewRoute,
} as any)
const AppEnrollmentNewAcademicRoute =
  AppEnrollmentNewAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => AppEnrollmentNewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/research-themes': typeof AppResearchThemesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/enrollment/new': typeof AppEnrollmentNewRouteWithChildren
  '/manage/enrollment-periods': typeof AppManageEnrollmentPeriodsRoute
  '/manage/professors': typeof AppManageProfessorsRoute
  '/manage/research-themes': typeof AppManageResearchThemesRoute
  '/validation/$enrollmentId': typeof AppValidationEnrollmentIdRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/enrollment/': typeof AppEnrollmentIndexRoute
  '/validation/': typeof AppValidationIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/enrollment/new/academic': typeof AppEnrollmentNewAcademicRoute
  '/enrollment/new/cv': typeof AppEnrollmentNewCvRoute
  '/enrollment/new/level': typeof AppEnrollmentNewLevelRoute
  '/enrollment/new/poscomp': typeof AppEnrollmentNewPoscompRoute
  '/enrollment/new/review': typeof AppEnrollmentNewReviewRoute
  '/enrollment/new/sigaa': typeof AppEnrollmentNewSigaaRoute
  '/enrollment/new/themes': typeof AppEnrollmentNewThemesRoute
  '/manage/enrollments/$id': typeof AppManageEnrollmentsIdRoute
  '/enrollment/new/': typeof AppEnrollmentNewIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/research-themes': typeof AppResearchThemesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/manage/enrollment-periods': typeof AppManageEnrollmentPeriodsRoute
  '/manage/professors': typeof AppManageProfessorsRoute
  '/manage/research-themes': typeof AppManageResearchThemesRoute
  '/validation/$enrollmentId': typeof AppValidationEnrollmentIdRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/enrollment': typeof AppEnrollmentIndexRoute
  '/validation': typeof AppValidationIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
  '/enrollment/new/academic': typeof AppEnrollmentNewAcademicRoute
  '/enrollment/new/cv': typeof AppEnrollmentNewCvRoute
  '/enrollment/new/level': typeof AppEnrollmentNewLevelRoute
  '/enrollment/new/poscomp': typeof AppEnrollmentNewPoscompRoute
  '/enrollment/new/review': typeof AppEnrollmentNewReviewRoute
  '/enrollment/new/sigaa': typeof AppEnrollmentNewSigaaRoute
  '/enrollment/new/themes': typeof AppEnrollmentNewThemesRoute
  '/manage/enrollments/$id': typeof AppManageEnrollmentsIdRoute
  '/enrollment/new': typeof AppEnrollmentNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/research-themes': typeof AppResearchThemesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/enrollment/new': typeof AppEnrollmentNewRouteWithChildren
  '/_app/manage/enrollment-periods': typeof AppManageEnrollmentPeriodsRoute
  '/_app/manage/professors': typeof AppManageProfessorsRoute
  '/_app/manage/research-themes': typeof AppManageResearchThemesRoute
  '/_app/validation/$enrollmentId': typeof AppValidationEnrollmentIdRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/_app/enrollment/': typeof AppEnrollmentIndexRoute
  '/_app/validation/': typeof AppValidationIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
  '/_app/enrollment/new/academic': typeof AppEnrollmentNewAcademicRoute
  '/_app/enrollment/new/cv': typeof AppEnrollmentNewCvRoute
  '/_app/enrollment/new/level': typeof AppEnrollmentNewLevelRoute
  '/_app/enrollment/new/poscomp': typeof AppEnrollmentNewPoscompRoute
  '/_app/enrollment/new/review': typeof AppEnrollmentNewReviewRoute
  '/_app/enrollment/new/sigaa': typeof AppEnrollmentNewSigaaRoute
  '/_app/enrollment/new/themes': typeof AppEnrollmentNewThemesRoute
  '/_app/manage/enrollments/$id': typeof AppManageEnrollmentsIdRoute
  '/_app/enrollment/new/': typeof AppEnrollmentNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/research-themes'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/enrollment/new'
    | '/manage/enrollment-periods'
    | '/manage/professors'
    | '/manage/research-themes'
    | '/validation/$enrollmentId'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/enrollment/'
    | '/validation/'
    | '/auth/onboarding/'
    | '/enrollment/new/academic'
    | '/enrollment/new/cv'
    | '/enrollment/new/level'
    | '/enrollment/new/poscomp'
    | '/enrollment/new/review'
    | '/enrollment/new/sigaa'
    | '/enrollment/new/themes'
    | '/manage/enrollments/$id'
    | '/enrollment/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/research-themes'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/manage/enrollment-periods'
    | '/manage/professors'
    | '/manage/research-themes'
    | '/validation/$enrollmentId'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/enrollment'
    | '/validation'
    | '/auth/onboarding'
    | '/enrollment/new/academic'
    | '/enrollment/new/cv'
    | '/enrollment/new/level'
    | '/enrollment/new/poscomp'
    | '/enrollment/new/review'
    | '/enrollment/new/sigaa'
    | '/enrollment/new/themes'
    | '/manage/enrollments/$id'
    | '/enrollment/new'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/research-themes'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/enrollment/new'
    | '/_app/manage/enrollment-periods'
    | '/_app/manage/professors'
    | '/_app/manage/research-themes'
    | '/_app/validation/$enrollmentId'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/_app/enrollment/'
    | '/_app/validation/'
    | '/auth/onboarding/'
    | '/_app/enrollment/new/academic'
    | '/_app/enrollment/new/cv'
    | '/_app/enrollment/new/level'
    | '/_app/enrollment/new/poscomp'
    | '/_app/enrollment/new/review'
    | '/_app/enrollment/new/sigaa'
    | '/_app/enrollment/new/themes'
    | '/_app/manage/enrollments/$id'
    | '/_app/enrollment/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-new-email': {
      id: '/auth/confirm-new-email'
      path: '/confirm-new-email'
      fullPath: '/auth/confirm-new-email'
      preLoaderRoute: typeof AuthConfirmNewEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/research-themes': {
      id: '/_app/research-themes'
      path: '/research-themes'
      fullPath: '/research-themes'
      preLoaderRoute: typeof AppResearchThemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/onboarding'
      fullPath: '/auth/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/validation/': {
      id: '/_app/validation/'
      path: '/validation'
      fullPath: '/validation/'
      preLoaderRoute: typeof AppValidationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/': {
      id: '/_app/enrollment/'
      path: '/enrollment'
      fullPath: '/enrollment/'
      preLoaderRoute: typeof AppEnrollmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/onboarding/secretary': {
      id: '/auth/onboarding/secretary'
      path: '/onboarding/secretary'
      fullPath: '/auth/onboarding/secretary'
      preLoaderRoute: typeof AuthOnboardingSecretaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding/professor': {
      id: '/auth/onboarding/professor'
      path: '/onboarding/professor'
      fullPath: '/auth/onboarding/professor'
      preLoaderRoute: typeof AuthOnboardingProfessorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/validation/$enrollmentId': {
      id: '/_app/validation/$enrollmentId'
      path: '/validation/$enrollmentId'
      fullPath: '/validation/$enrollmentId'
      preLoaderRoute: typeof AppValidationEnrollmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/research-themes': {
      id: '/_app/manage/research-themes'
      path: '/manage/research-themes'
      fullPath: '/manage/research-themes'
      preLoaderRoute: typeof AppManageResearchThemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/professors': {
      id: '/_app/manage/professors'
      path: '/manage/professors'
      fullPath: '/manage/professors'
      preLoaderRoute: typeof AppManageProfessorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/enrollment-periods': {
      id: '/_app/manage/enrollment-periods'
      path: '/manage/enrollment-periods'
      fullPath: '/manage/enrollment-periods'
      preLoaderRoute: typeof AppManageEnrollmentPeriodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/new': {
      id: '/_app/enrollment/new'
      path: '/enrollment/new'
      fullPath: '/enrollment/new'
      preLoaderRoute: typeof AppEnrollmentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/new/': {
      id: '/_app/enrollment/new/'
      path: '/'
      fullPath: '/enrollment/new/'
      preLoaderRoute: typeof AppEnrollmentNewIndexRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/manage/enrollments/$id': {
      id: '/_app/manage/enrollments/$id'
      path: '/manage/enrollments/$id'
      fullPath: '/manage/enrollments/$id'
      preLoaderRoute: typeof AppManageEnrollmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enrollment/new/themes': {
      id: '/_app/enrollment/new/themes'
      path: '/themes'
      fullPath: '/enrollment/new/themes'
      preLoaderRoute: typeof AppEnrollmentNewThemesRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/sigaa': {
      id: '/_app/enrollment/new/sigaa'
      path: '/sigaa'
      fullPath: '/enrollment/new/sigaa'
      preLoaderRoute: typeof AppEnrollmentNewSigaaRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/review': {
      id: '/_app/enrollment/new/review'
      path: '/review'
      fullPath: '/enrollment/new/review'
      preLoaderRoute: typeof AppEnrollmentNewReviewRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/poscomp': {
      id: '/_app/enrollment/new/poscomp'
      path: '/poscomp'
      fullPath: '/enrollment/new/poscomp'
      preLoaderRoute: typeof AppEnrollmentNewPoscompRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/level': {
      id: '/_app/enrollment/new/level'
      path: '/level'
      fullPath: '/enrollment/new/level'
      preLoaderRoute: typeof AppEnrollmentNewLevelRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/cv': {
      id: '/_app/enrollment/new/cv'
      path: '/cv'
      fullPath: '/enrollment/new/cv'
      preLoaderRoute: typeof AppEnrollmentNewCvRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
    '/_app/enrollment/new/academic': {
      id: '/_app/enrollment/new/academic'
      path: '/academic'
      fullPath: '/enrollment/new/academic'
      preLoaderRoute: typeof AppEnrollmentNewAcademicRouteImport
      parentRoute: typeof AppEnrollmentNewRoute
    }
  }
}

interface AppEnrollmentNewRouteChildren {
  AppEnrollmentNewAcademicRoute: typeof AppEnrollmentNewAcademicRoute
  AppEnrollmentNewCvRoute: typeof AppEnrollmentNewCvRoute
  AppEnrollmentNewLevelRoute: typeof AppEnrollmentNewLevelRoute
  AppEnrollmentNewPoscompRoute: typeof AppEnrollmentNewPoscompRoute
  AppEnrollmentNewReviewRoute: typeof AppEnrollmentNewReviewRoute
  AppEnrollmentNewSigaaRoute: typeof AppEnrollmentNewSigaaRoute
  AppEnrollmentNewThemesRoute: typeof AppEnrollmentNewThemesRoute
  AppEnrollmentNewIndexRoute: typeof AppEnrollmentNewIndexRoute
}

const AppEnrollmentNewRouteChildren: AppEnrollmentNewRouteChildren = {
  AppEnrollmentNewAcademicRoute: AppEnrollmentNewAcademicRoute,
  AppEnrollmentNewCvRoute: AppEnrollmentNewCvRoute,
  AppEnrollmentNewLevelRoute: AppEnrollmentNewLevelRoute,
  AppEnrollmentNewPoscompRoute: AppEnrollmentNewPoscompRoute,
  AppEnrollmentNewReviewRoute: AppEnrollmentNewReviewRoute,
  AppEnrollmentNewSigaaRoute: AppEnrollmentNewSigaaRoute,
  AppEnrollmentNewThemesRoute: AppEnrollmentNewThemesRoute,
  AppEnrollmentNewIndexRoute: AppEnrollmentNewIndexRoute,
}

const AppEnrollmentNewRouteWithChildren =
  AppEnrollmentNewRoute._addFileChildren(AppEnrollmentNewRouteChildren)

interface AppRouteChildren {
  AppResearchThemesRoute: typeof AppResearchThemesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEnrollmentNewRoute: typeof AppEnrollmentNewRouteWithChildren
  AppManageEnrollmentPeriodsRoute: typeof AppManageEnrollmentPeriodsRoute
  AppManageProfessorsRoute: typeof AppManageProfessorsRoute
  AppManageResearchThemesRoute: typeof AppManageResearchThemesRoute
  AppValidationEnrollmentIdRoute: typeof AppValidationEnrollmentIdRoute
  AppEnrollmentIndexRoute: typeof AppEnrollmentIndexRoute
  AppValidationIndexRoute: typeof AppValidationIndexRoute
  AppManageEnrollmentsIdRoute: typeof AppManageEnrollmentsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppResearchThemesRoute: AppResearchThemesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEnrollmentNewRoute: AppEnrollmentNewRouteWithChildren,
  AppManageEnrollmentPeriodsRoute: AppManageEnrollmentPeriodsRoute,
  AppManageProfessorsRoute: AppManageProfessorsRoute,
  AppManageResearchThemesRoute: AppManageResearchThemesRoute,
  AppValidationEnrollmentIdRoute: AppValidationEnrollmentIdRoute,
  AppEnrollmentIndexRoute: AppEnrollmentIndexRoute,
  AppValidationIndexRoute: AppValidationIndexRoute,
  AppManageEnrollmentsIdRoute: AppManageEnrollmentsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthConfirmNewEmailRoute: typeof AuthConfirmNewEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthOnboardingProfessorRoute: typeof AuthOnboardingProfessorRoute
  AuthOnboardingSecretaryRoute: typeof AuthOnboardingSecretaryRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthConfirmNewEmailRoute: AuthConfirmNewEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthOnboardingProfessorRoute: AuthOnboardingProfessorRoute,
  AuthOnboardingSecretaryRoute: AuthOnboardingSecretaryRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
