/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmNewEmailRouteImport } from './routes/auth/confirm-new-email'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth/confirm-email'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AuthOnboardingIndexRouteImport } from './routes/auth/onboarding/index'
import { Route as AppProfessorsIndexRouteImport } from './routes/_app/professors/index'
import { Route as AuthOnboardingSecretaryRouteImport } from './routes/auth/onboarding/secretary'
import { Route as AuthOnboardingProfessorRouteImport } from './routes/auth/onboarding/professor'
import { Route as AppManageProfessorsRouteImport } from './routes/_app/manage/professors'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmNewEmailRoute = AuthConfirmNewEmailRouteImport.update({
  id: '/confirm-new-email',
  path: '/confirm-new-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingIndexRoute = AuthOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthRoute,
} as any)
const AppProfessorsIndexRoute = AppProfessorsIndexRouteImport.update({
  id: '/professors/',
  path: '/professors/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOnboardingSecretaryRoute = AuthOnboardingSecretaryRouteImport.update({
  id: '/onboarding/secretary',
  path: '/onboarding/secretary',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingProfessorRoute = AuthOnboardingProfessorRouteImport.update({
  id: '/onboarding/professor',
  path: '/onboarding/professor',
  getParentRoute: () => AuthRoute,
} as any)
const AppManageProfessorsRoute = AppManageProfessorsRouteImport.update({
  id: '/manage/professors',
  path: '/manage/professors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/manage/professors': typeof AppManageProfessorsRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/professors/': typeof AppProfessorsIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/manage/professors': typeof AppManageProfessorsRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/professors': typeof AppProfessorsIndexRoute
  '/auth/onboarding': typeof AuthOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-new-email': typeof AuthConfirmNewEmailRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/manage/professors': typeof AppManageProfessorsRoute
  '/auth/onboarding/professor': typeof AuthOnboardingProfessorRoute
  '/auth/onboarding/secretary': typeof AuthOnboardingSecretaryRoute
  '/_app/professors/': typeof AppProfessorsIndexRoute
  '/auth/onboarding/': typeof AuthOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/manage/professors'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/professors/'
    | '/auth/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/manage/professors'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/professors'
    | '/auth/onboarding'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/confirm-new-email'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/manage/professors'
    | '/auth/onboarding/professor'
    | '/auth/onboarding/secretary'
    | '/_app/professors/'
    | '/auth/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-new-email': {
      id: '/auth/confirm-new-email'
      path: '/confirm-new-email'
      fullPath: '/auth/confirm-new-email'
      preLoaderRoute: typeof AuthConfirmNewEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding/': {
      id: '/auth/onboarding/'
      path: '/onboarding'
      fullPath: '/auth/onboarding/'
      preLoaderRoute: typeof AuthOnboardingIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/professors/': {
      id: '/_app/professors/'
      path: '/professors'
      fullPath: '/professors/'
      preLoaderRoute: typeof AppProfessorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/onboarding/secretary': {
      id: '/auth/onboarding/secretary'
      path: '/onboarding/secretary'
      fullPath: '/auth/onboarding/secretary'
      preLoaderRoute: typeof AuthOnboardingSecretaryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding/professor': {
      id: '/auth/onboarding/professor'
      path: '/onboarding/professor'
      fullPath: '/auth/onboarding/professor'
      preLoaderRoute: typeof AuthOnboardingProfessorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/manage/professors': {
      id: '/_app/manage/professors'
      path: '/manage/professors'
      fullPath: '/manage/professors'
      preLoaderRoute: typeof AppManageProfessorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppManageProfessorsRoute: typeof AppManageProfessorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppManageProfessorsRoute: AppManageProfessorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthConfirmNewEmailRoute: typeof AuthConfirmNewEmailRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthOnboardingProfessorRoute: typeof AuthOnboardingProfessorRoute
  AuthOnboardingSecretaryRoute: typeof AuthOnboardingSecretaryRoute
  AuthOnboardingIndexRoute: typeof AuthOnboardingIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthConfirmNewEmailRoute: AuthConfirmNewEmailRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthOnboardingProfessorRoute: AuthOnboardingProfessorRoute,
  AuthOnboardingSecretaryRoute: AuthOnboardingSecretaryRoute,
  AuthOnboardingIndexRoute: AuthOnboardingIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
